### ISSUE TITLE
Support a `--workspaces` and maybe `--workspace` flag to run in a npm workspace monorepo

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/node-installed-check#31]

**Comment by voxpelli** [comment]
Inspiration:

* https://www.npmjs.com/package/@npmcli/map-workspaces
* https://www.npmjs.com/package/yarn-changed-workspaces

**Comment by vitaminj** [comment]
I tried to support this usecase manually by re-running `installed-check` in our multiple workspace subdirectories, but because all of the deps are installed in `node_modules` in the root, `installed-check` will fail with "Non-existing path" looking for a `node_modules` next to the `package.json`, whereas node and bundlers will traverse your file tree up and up looking for more `node_modules` directories.
Do you have any suggestions on how to do this in a manual way? Or just be able to say "look at _that_ nested `package.json`(s), but look in _this_ `node_modules`"

**Comment by vitaminj** [comment]
I've done a naïve hack that works for our usecases - perhaps this can serve as either useful for anyone else, or a starting point for a more legitimate implementation?
https://github.com/youviewtv/node-installed-check-core/compare/main...workspaces
